services:
  base:
    user: root
    restart: unless-stopped
    image: kumbukum-dev:local
    volumes:
      - ./:/opt/kumbukum
      - node_modules:/opt/kumbukum/node_modules
      - pnpm_store:/pnpm/store
