services:
  base:
    user: root
    restart: unless-stopped
    image: streamient-dev:local
    volumes:
      - ./:/opt/streamient
      - node_modules:/opt/streamient/node_modules
      - pnpm_store:/pnpm/store
